[project]
name = "taller-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "great-expectations>=1.9.1",
    "pandas>=2.3.3",
    "pandera>=0.26.1",
    "pytest>=9.0.1",
    "pytest-html>=4.1.1",
]
